name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build pages
        run: |
          mkdir -p dist/privacy-policy/de
          npx --yes marked -i pages/privacy-policy/de.md -o dist/privacy-policy/de/index.html
          mkdir -p dist/privacy-policy/fr
          npx --yes marked -i pages/privacy-policy/fr.md -o dist/privacy-policy/fr/index.html
          mkdir -p dist/terms-and-conditions/de
          npx --yes marked -i pages/terms-and-conditions/de.md -o dist/terms-and-conditions/de/index.html
          mkdir -p dist/terms-and-conditions/fr
          npx --yes marked -i pages/terms-and-conditions/fr.md -o dist/terms-and-conditions/fr/index.html
        working-directory: ${{ env.BUILD_PATH }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
